Updated to `Gymnasium v0.26.2`
Farama-Foundation/Miniworld pull request #72
Opened 2022-10-16 14:54 UTC by BolunDai0216

# Description

Changed the dependency on `gym` to `gymnasium` at `v0.26.2`. 

Fixes # (issue)

A list of the changes:

- Changed the output of `step` from `obs, reward, done, info` to `obs, reward, done, truncation, info`.
- Removed `return_info` in `reset()` and returns `obs, info` all the time.
- Added `render_mode` to the environments.
- Changed the tests to use `gymnasium` and adapt to the new output of `reset()` and `step()`.
- Removed `seed()`

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-10-16 19:05 UTC, pseudo-rnd-thoughts requested changes
Could you make the suggested changes. 
Is there a test that runs check_env with all of the miniworld envs ?
This is for a future pr or release where we change the randomness to use the env.np_random

2022-10-16 19:05 UTC, pseudo-rnd-thoughts commented on gym_miniworld/envs/remotebot.py
> +    def render(self, close=False):
Can we move the close code to the close function

2022-10-16 19:05 UTC, pseudo-rnd-thoughts commented on gym_miniworld/envs/sign.py
>      ) -> Union[ObsType, Tuple[ObsType, dict]]:
This should just be the tuple type now

2022-10-16 19:05 UTC, pseudo-rnd-thoughts commented on gym_miniworld/miniworld.py
>      ) -> Union[ObsType, Tuple[ObsType, dict]]:
Only use tuple type

2022-10-16 19:05 UTC, pseudo-rnd-thoughts commented on gym_miniworld/miniworld.py
> +    def render(self, close=False, view="agent"):
Can we move view to __init__ and close code to the close function

2022-10-16 19:05 UTC, pseudo-rnd-thoughts commented on requirements.txt
> +gym==0.26.2
Remove

2022-10-16 19:05 UTC, pseudo-rnd-thoughts commented on requirements.txt
> +gym-notices==0.0.8
Remove

2022-10-16 19:05 UTC, pseudo-rnd-thoughts commented on setup.py
> +        "gym>=0.26.2",
Remove

2022-10-16 22:12 UTC, BolunDai0216 commented on gym_miniworld/envs/remotebot.py
> +    def reset(self, seed, options):
Yeah. I noticed that the type hint situation is not consistent, some functions have it others don't. Is there a guideline? Or should we just add type hints to all of the functions?

2022-10-16 22:17 UTC, BolunDai0216 commented
> Could you make the suggested changes. Is there a test that runs check_env with all of the miniworld envs ? This is for a future pr or release where we change the randomness to use the env.np_random

`test_env_checker()` runs `check_env()` on all of the environments

```python
@pytest.mark.parametrize("env_id", gym_miniworld.envs.env_ids)
def test_env_checker(env_id):
    if "RemoteBot" in env_id:
        return

    env = gym.make(env_id).unwrapped
    warnings.simplefilter("always")
    with warnings.catch_warnings(record=True) as w:
        check_env(env)

    for warning in w:
        if warning.message.args[0] not in CHECK_ENV_IGNORE_WARNINGS:
            raise gym.error.Error(f"Unexpected warning: {warning.message}")

    env.close()
```

2022-10-17 09:41 UTC, pseudo-rnd-thoughts commented on gym_miniworld/envs/remotebot.py
> +    def reset(self, seed, options):
At some point, it would be great to type hint the whole project but for now just having most of the critical sections of the project would be best

2022-10-21 23:16 UTC, merged